import mongoose from "mongoose"

const MONGODB_URI = process.env.MONGODB_URI!

const ProductSchema = new mongoose.Schema({
  store: String, slug: String, name: String,
  price: String, tag: String, inStock: Boolean,
  category: String, description: String,
  sizes: [String], colors: [String], images: [String],
  gender: String, subcategory: String,
})

const Product = mongoose.models.Product || mongoose.model("Product", ProductSchema)

const products = [
  // ZARA WOMEN
  { store: "Zara", slug: "zara", gender: "Women", subcategory: "Blazers", name: "Oversized Blazer", price: "$89.99", tag: "New", inStock: true, category: "Fashion & Basics", description: "A sophisticated oversized blazer crafted from a premium blend fabric.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Camel", "White"] },
  { store: "Zara", slug: "zara", gender: "Women", subcategory: "Trousers", name: "Wide Leg Trousers", price: "$49.99", tag: "Trending", inStock: true, category: "Fashion & Basics", description: "High-waisted wide leg trousers with a fluid drape.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Cream", "Navy"] },
  { store: "Zara", slug: "zara", gender: "Women", subcategory: "Tops", name: "Ribbed Knit Top", price: "$29.99", tag: "", inStock: true, category: "Fashion & Basics", description: "A fitted ribbed knit top with a crew neck.", sizes: ["XS", "S", "M", "L"], colors: ["Black", "White", "Brown", "Grey"] },
  { store: "Zara", slug: "zara", gender: "Women", subcategory: "Skirts", name: "Leather Mini Skirt", price: "$69.99", tag: "New", inStock: true, category: "Fashion & Basics", description: "Faux leather mini skirt with a sleek finish.", sizes: ["XS", "S", "M", "L"], colors: ["Black", "Burgundy"] },
  { store: "Zara", slug: "zara", gender: "Women", subcategory: "Jackets & Coats", name: "Trench Coat", price: "$129.99", tag: "Trending", inStock: true, category: "Fashion & Basics", description: "Classic double-breasted trench coat with a belted waist.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Camel", "Black", "Beige"] },
  { store: "Zara", slug: "zara", gender: "Women", subcategory: "Dresses", name: "Satin Slip Dress", price: "$59.99", tag: "", inStock: true, category: "Fashion & Basics", description: "Elegant satin slip dress with adjustable straps.", sizes: ["XS", "S", "M", "L"], colors: ["Black", "Champagne", "Dusty Rose"] },
  // ZARA MEN
  { store: "Zara", slug: "zara", gender: "Men", subcategory: "Jackets & Coats", name: "Wool Blend Coat", price: "$149.99", tag: "New", inStock: true, category: "Fashion & Basics", description: "Tailored wool blend coat with a relaxed fit.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Camel", "Black", "Grey"] },
  { store: "Zara", slug: "zara", gender: "Men", subcategory: "Trousers", name: "Slim Fit Chinos", price: "$49.99", tag: "", inStock: true, category: "Fashion & Basics", description: "Smart slim fit chinos in premium cotton.", sizes: ["28", "30", "32", "34", "36"], colors: ["Beige", "Navy", "Black"] },
  { store: "Zara", slug: "zara", gender: "Men", subcategory: "Tops", name: "Linen Shirt", price: "$39.99", tag: "Trending", inStock: true, category: "Fashion & Basics", description: "Relaxed linen shirt perfect for warm weather.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["White", "Blue", "Beige"] },
  { store: "Zara", slug: "zara", gender: "Men", subcategory: "Tops", name: "Knit Polo", price: "$45.99", tag: "New", inStock: true, category: "Fashion & Basics", description: "Fine knit polo with a classic collar.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Navy", "Green"] },
  { store: "Zara", slug: "zara", gender: "Men", subcategory: "Trousers", name: "Wide Leg Trousers", price: "$55.99", tag: "", inStock: true, category: "Fashion & Basics", description: "Relaxed wide leg trousers in a premium fabric.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey", "Beige"] },
  { store: "Zara", slug: "zara", gender: "Men", subcategory: "Blazers", name: "Structured Blazer", price: "$99.99", tag: "Trending", inStock: true, category: "Fashion & Basics", description: "Sharp structured blazer for a polished look.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Navy", "Grey"] },
  // UNIQLO WOMEN
  { store: "Uniqlo", slug: "uniqlo", gender: "Women", subcategory: "Tops", name: "Heattech Turtleneck", price: "$34.99", tag: "Bestseller", inStock: true, category: "Essentials & Comfort", description: "Uniqlo's iconic Heattech in a slim turtleneck.", sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Black", "White", "Navy", "Grey"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Women", subcategory: "Jackets & Coats", name: "Ultra Light Down Jacket", price: "$79.99", tag: "New", inStock: true, category: "Essentials & Comfort", description: "Packable down jacket with exceptional warmth.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Navy", "Olive", "Red"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Women", subcategory: "Trousers", name: "Relaxed Fit Chinos", price: "$44.99", tag: "", inStock: true, category: "Essentials & Comfort", description: "Comfortable relaxed fit chinos in soft cotton.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Beige", "Navy", "Black"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Women", subcategory: "Tops", name: "Cotton Crew T-Shirt", price: "$14.99", tag: "", inStock: true, category: "Essentials & Comfort", description: "100% premium cotton crew neck tee.", sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["White", "Black", "Grey", "Navy", "Beige"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Women", subcategory: "Jeans", name: "Wide Fit Jeans", price: "$49.99", tag: "New", inStock: true, category: "Essentials & Comfort", description: "Wide leg jeans with a high rise waist.", sizes: ["24", "26", "28", "30", "32"], colors: ["Light Blue", "Dark Blue", "Black"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Women", subcategory: "Tops", name: "Fleece Pullover", price: "$39.99", tag: "Trending", inStock: true, category: "Essentials & Comfort", description: "Cozy fleece pullover with a classic fit.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Grey", "Navy", "Black"] },
  // UNIQLO MEN
  { store: "Uniqlo", slug: "uniqlo", gender: "Men", subcategory: "Tops", name: "Heattech Crewneck", price: "$29.99", tag: "Bestseller", inStock: true, category: "Essentials & Comfort", description: "Heattech base layer with a classic crew neck.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "White", "Navy", "Grey"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Men", subcategory: "Jackets & Coats", name: "Ultra Light Down Puffer", price: "$89.99", tag: "New", inStock: true, category: "Essentials & Comfort", description: "Lightweight packable puffer jacket.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "Navy", "Olive"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Men", subcategory: "Trousers", name: "Slim Fit Chinos", price: "$44.99", tag: "", inStock: true, category: "Essentials & Comfort", description: "Versatile slim chinos for work or weekend.", sizes: ["28", "30", "32", "34", "36"], colors: ["Beige", "Navy", "Olive", "Black"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Men", subcategory: "Tops", name: "Flannel Shirt", price: "$39.99", tag: "Trending", inStock: true, category: "Essentials & Comfort", description: "Soft flannel shirt in a relaxed fit.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Navy", "Red", "Green"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Men", subcategory: "Tops", name: "Merino Crew Sweater", price: "$59.99", tag: "New", inStock: true, category: "Essentials & Comfort", description: "Fine merino wool crew neck sweater.", sizes: ["S", "M", "L", "XL"], colors: ["Oatmeal", "Black", "Navy"] },
  { store: "Uniqlo", slug: "uniqlo", gender: "Men", subcategory: "Jeans", name: "Slim Straight Jeans", price: "$49.99", tag: "", inStock: true, category: "Essentials & Comfort", description: "Classic slim straight jeans in stretch denim.", sizes: ["28", "30", "32", "34", "36"], colors: ["Dark Blue", "Black", "Light Blue"] },
  // H&M WOMEN
  { store: "H&M", slug: "hm", gender: "Women", subcategory: "Trousers", name: "Cargo Pants", price: "$39.99", tag: "Trending", inStock: true, category: "Trends & Streetwear", description: "Relaxed fit cargo pants with multiple pockets.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Khaki", "Black", "Grey"] },
  { store: "H&M", slug: "hm", gender: "Women", subcategory: "Tops", name: "Graphic Hoodie", price: "$34.99", tag: "New", inStock: true, category: "Trends & Streetwear", description: "Oversized graphic hoodie in soft fleece.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "White", "Grey"] },
  { store: "H&M", slug: "hm", gender: "Women", subcategory: "Jackets & Coats", name: "Denim Jacket", price: "$49.99", tag: "", inStock: true, category: "Trends & Streetwear", description: "Classic denim jacket with a slightly oversized fit.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Light Blue", "Dark Blue", "Black"] },
  { store: "H&M", slug: "hm", gender: "Women", subcategory: "Dresses", name: "Bodycon Dress", price: "$29.99", tag: "Trending", inStock: true, category: "Trends & Streetwear", description: "Stretchy bodycon dress with a figure-hugging silhouette.", sizes: ["XS", "S", "M", "L"], colors: ["Black", "Red", "Nude"] },
  { store: "H&M", slug: "hm", gender: "Women", subcategory: "Tops", name: "Oversized Tee", price: "$19.99", tag: "", inStock: true, category: "Trends & Streetwear", description: "Dropped shoulder oversized tee in cotton jersey.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["White", "Black", "Grey", "Beige"] },
  { store: "H&M", slug: "hm", gender: "Women", subcategory: "Skirts", name: "Pleated Midi Skirt", price: "$34.99", tag: "New", inStock: true, category: "Trends & Streetwear", description: "Flowy pleated midi skirt with elastic waistband.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Pink", "Sage Green"] },
  // H&M MEN
  { store: "H&M", slug: "hm", gender: "Men", subcategory: "Trousers", name: "Cargo Trousers", price: "$44.99", tag: "Trending", inStock: true, category: "Trends & Streetwear", description: "Utility cargo trousers with zip pockets.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Khaki", "Black", "Grey"] },
  { store: "H&M", slug: "hm", gender: "Men", subcategory: "Tops", name: "Oversized Hoodie", price: "$39.99", tag: "New", inStock: true, category: "Trends & Streetwear", description: "Relaxed fit hoodie in heavy fleece fabric.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "Grey", "White"] },
  { store: "H&M", slug: "hm", gender: "Men", subcategory: "Jackets & Coats", name: "Bomber Jacket", price: "$59.99", tag: "Trending", inStock: true, category: "Trends & Streetwear", description: "Classic bomber jacket with ribbed cuffs.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Olive", "Navy"] },
  { store: "H&M", slug: "hm", gender: "Men", subcategory: "Tops", name: "Printed Tee", price: "$19.99", tag: "", inStock: true, category: "Trends & Streetwear", description: "Bold graphic tee in soft cotton jersey.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "White"] },
  { store: "H&M", slug: "hm", gender: "Men", subcategory: "Jeans", name: "Slim Jeans", price: "$39.99", tag: "", inStock: true, category: "Trends & Streetwear", description: "Slim fit jeans in stretch denim.", sizes: ["28", "30", "32", "34"], colors: ["Dark Blue", "Black", "Light Blue"] },
  { store: "H&M", slug: "hm", gender: "Men", subcategory: "Tops", name: "Knit Sweater", price: "$34.99", tag: "New", inStock: true, category: "Trends & Streetwear", description: "Cozy knit sweater in a relaxed fit.", sizes: ["S", "M", "L", "XL"], colors: ["Grey", "Navy", "Brown"] },
  // NIKE WOMEN
  { store: "Nike", slug: "nike", gender: "Women", subcategory: "Shoes", name: "Air Max Pulse", price: "$149.99", tag: "New", inStock: true, category: "Sport & Lifestyle", description: "The Air Max Pulse with visible Air cushioning.", sizes: ["6", "7", "8", "9", "10"], colors: ["White/Black", "Black/Grey", "Triple Black"] },
  { store: "Nike", slug: "nike", gender: "Women", subcategory: "Tops", name: "Dri-FIT T-Shirt", price: "$34.99", tag: "", inStock: true, category: "Sport & Lifestyle", description: "Nike Dri-FIT technology for quick evaporation.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "White", "Grey", "Blue"] },
  { store: "Nike", slug: "nike", gender: "Women", subcategory: "Tops", name: "Tech Fleece Hoodie", price: "$109.99", tag: "Trending", inStock: true, category: "Sport & Lifestyle", description: "Lightweight warmth with a modern athletic look.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Grey", "Navy"] },
  { store: "Nike", slug: "nike", gender: "Women", subcategory: "Shorts", name: "Running Shorts", price: "$44.99", tag: "", inStock: true, category: "Sport & Lifestyle", description: "Lightweight shorts with built-in briefs.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Navy", "Grey"] },
  { store: "Nike", slug: "nike", gender: "Women", subcategory: "Shoes", name: "Air Force 1", price: "$109.99", tag: "Bestseller", inStock: true, category: "Sport & Lifestyle", description: "A hoops icon turned street essential.", sizes: ["6", "7", "8", "9", "10"], colors: ["White", "Black", "Triple White"] },
  { store: "Nike", slug: "nike", gender: "Women", subcategory: "Jackets & Coats", name: "Windrunner Jacket", price: "$129.99", tag: "New", inStock: true, category: "Sport & Lifestyle", description: "Wind-resistant with a packable hood.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black/White", "Navy/Red", "Grey"] },
  // NIKE MEN
  { store: "Nike", slug: "nike", gender: "Men", subcategory: "Shoes", name: "Air Max 90", price: "$129.99", tag: "Bestseller", inStock: true, category: "Sport & Lifestyle", description: "Classic Air Max 90 with Max Air heel unit.", sizes: ["7", "8", "9", "10", "11", "12"], colors: ["White/Grey", "Black/Red", "Triple White"] },
  { store: "Nike", slug: "nike", gender: "Men", subcategory: "Tops", name: "Tech Fleece Crewneck", price: "$99.99", tag: "New", inStock: true, category: "Sport & Lifestyle", description: "Nike Tech Fleece crewneck with modern taper.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "Grey", "Navy"] },
  { store: "Nike", slug: "nike", gender: "Men", subcategory: "Tops", name: "Dri-FIT Training Tee", price: "$29.99", tag: "", inStock: true, category: "Sport & Lifestyle", description: "Moisture-wicking training tee for performance.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "White", "Grey"] },
  { store: "Nike", slug: "nike", gender: "Men", subcategory: "Shorts", name: "Club Fleece Shorts", price: "$44.99", tag: "", inStock: true, category: "Sport & Lifestyle", description: "Soft fleece shorts with an elastic waistband.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "Grey", "Navy"] },
  { store: "Nike", slug: "nike", gender: "Men", subcategory: "Shoes", name: "Air Force 1 Low", price: "$109.99", tag: "Trending", inStock: true, category: "Sport & Lifestyle", description: "The legendary low-top street icon.", sizes: ["7", "8", "9", "10", "11", "12"], colors: ["White", "Black", "Wheat"] },
  { store: "Nike", slug: "nike", gender: "Men", subcategory: "Jackets & Coats", name: "Sportswear Windrunner", price: "$139.99", tag: "New", inStock: true, category: "Sport & Lifestyle", description: "Iconic chevron design in wind-resistant fabric.", sizes: ["S", "M", "L", "XL"], colors: ["Black/White", "Navy/Red"] },
  // COS WOMEN
  { store: "COS", slug: "cos", gender: "Women", subcategory: "Blazers", name: "Structured Blazer", price: "$179.99", tag: "New", inStock: true, category: "Minimal & Modern", description: "Precisely tailored blazer in premium wool blend.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Ivory", "Camel"] },
  { store: "COS", slug: "cos", gender: "Women", subcategory: "Trousers", name: "Wide Leg Pants", price: "$89.99", tag: "", inStock: true, category: "Minimal & Modern", description: "Fluid wide leg trousers with clean front.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Ecru", "Slate Grey"] },
  { store: "COS", slug: "cos", gender: "Women", subcategory: "Tops", name: "Merino Knit", price: "$99.99", tag: "Trending", inStock: true, category: "Minimal & Modern", description: "Fine merino wool knit with relaxed boxy fit.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Oatmeal", "Black", "Forest Green"] },
  { store: "COS", slug: "cos", gender: "Women", subcategory: "Jackets & Coats", name: "Oversized Coat", price: "$249.99", tag: "New", inStock: true, category: "Minimal & Modern", description: "Voluminous oversized coat in premium wool blend.", sizes: ["XS", "S", "M", "L"], colors: ["Camel", "Black", "Grey"] },
  { store: "COS", slug: "cos", gender: "Women", subcategory: "Tops", name: "Silk Blouse", price: "$119.99", tag: "", inStock: true, category: "Minimal & Modern", description: "Relaxed silk blouse with fluid drape.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["White", "Black", "Dusty Blue"] },
  { store: "COS", slug: "cos", gender: "Women", subcategory: "Shorts", name: "Tailored Shorts", price: "$79.99", tag: "", inStock: true, category: "Minimal & Modern", description: "Precisely cut tailored shorts in premium fabric.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Ecru", "Navy"] },
  // COS MEN
  { store: "COS", slug: "cos", gender: "Men", subcategory: "Blazers", name: "Relaxed Fit Blazer", price: "$189.99", tag: "New", inStock: true, category: "Minimal & Modern", description: "Unstructured blazer with a clean minimal aesthetic.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Navy", "Grey"] },
  { store: "COS", slug: "cos", gender: "Men", subcategory: "Trousers", name: "Tapered Trousers", price: "$89.99", tag: "", inStock: true, category: "Minimal & Modern", description: "Clean tapered trousers in premium fabric.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey", "Navy"] },
  { store: "COS", slug: "cos", gender: "Men", subcategory: "Tops", name: "Oversized Merino Knit", price: "$109.99", tag: "Trending", inStock: true, category: "Minimal & Modern", description: "Relaxed merino knit with a boxy silhouette.", sizes: ["S", "M", "L", "XL"], colors: ["Oatmeal", "Black", "Forest Green"] },
  { store: "COS", slug: "cos", gender: "Men", subcategory: "Tops", name: "Poplin Shirt", price: "$79.99", tag: "", inStock: true, category: "Minimal & Modern", description: "Crisp poplin shirt with a relaxed fit.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["White", "Black", "Blue"] },
  { store: "COS", slug: "cos", gender: "Men", subcategory: "Jackets & Coats", name: "Wool Overcoat", price: "$259.99", tag: "New", inStock: true, category: "Minimal & Modern", description: "Long wool overcoat with clean minimal detailing.", sizes: ["S", "M", "L", "XL"], colors: ["Camel", "Black", "Grey"] },
  { store: "COS", slug: "cos", gender: "Men", subcategory: "Trousers", name: "Wide Leg Trousers", price: "$89.99", tag: "", inStock: true, category: "Minimal & Modern", description: "Fluid wide leg trousers in premium fabric.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Ecru", "Navy"] },
  // MANGO WOMEN
  { store: "Mango", slug: "mango", gender: "Women", subcategory: "Blazers", name: "Linen Blazer", price: "$99.99", tag: "New", inStock: true, category: "Mediterranean Style", description: "Relaxed linen blazer perfect for warm weather.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["White", "Beige", "Navy"] },
  { store: "Mango", slug: "mango", gender: "Women", subcategory: "Dresses", name: "Floral Midi Dress", price: "$69.99", tag: "Trending", inStock: true, category: "Mediterranean Style", description: "Romantic floral print midi dress with wrap silhouette.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Blue Floral", "Pink Floral", "Black Floral"] },
  { store: "Mango", slug: "mango", gender: "Women", subcategory: "Bags", name: "Leather Tote", price: "$79.99", tag: "", inStock: true, category: "Mediterranean Style", description: "Spacious leather tote with interior pockets.", sizes: ["One Size"], colors: ["Black", "Tan", "White"] },
  { store: "Mango", slug: "mango", gender: "Women", subcategory: "Tops", name: "Striped Knit", price: "$49.99", tag: "", inStock: true, category: "Mediterranean Style", description: "Classic striped knit top with relaxed fit.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Navy/White", "Black/White"] },
  { store: "Mango", slug: "mango", gender: "Women", subcategory: "Accessories", name: "Wide Brim Hat", price: "$39.99", tag: "New", inStock: true, category: "Mediterranean Style", description: "Woven wide brim hat with UV protection.", sizes: ["One Size"], colors: ["Natural", "Black", "Camel"] },
  { store: "Mango", slug: "mango", gender: "Women", subcategory: "Trousers", name: "Linen Trousers", price: "$59.99", tag: "Trending", inStock: true, category: "Mediterranean Style", description: "Breathable linen trousers with relaxed straight leg.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["White", "Beige", "Black"] },
  // MANGO MEN
  { store: "Mango", slug: "mango", gender: "Men", subcategory: "Tops", name: "Linen Shirt", price: "$59.99", tag: "New", inStock: true, category: "Mediterranean Style", description: "Breathable linen shirt for warm weather.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["White", "Beige", "Blue"] },
  { store: "Mango", slug: "mango", gender: "Men", subcategory: "Trousers", name: "Linen Trousers", price: "$65.99", tag: "Trending", inStock: true, category: "Mediterranean Style", description: "Relaxed linen trousers with drawstring waist.", sizes: ["S", "M", "L", "XL"], colors: ["White", "Beige", "Navy"] },
  { store: "Mango", slug: "mango", gender: "Men", subcategory: "Blazers", name: "Linen Blazer", price: "$109.99", tag: "", inStock: true, category: "Mediterranean Style", description: "Unstructured linen blazer for a relaxed look.", sizes: ["S", "M", "L", "XL"], colors: ["Beige", "Navy", "White"] },
  { store: "Mango", slug: "mango", gender: "Men", subcategory: "Tops", name: "Striped Polo", price: "$45.99", tag: "", inStock: true, category: "Mediterranean Style", description: "Classic striped polo in breathable pique fabric.", sizes: ["S", "M", "L", "XL"], colors: ["Navy/White", "Red/White"] },
  { store: "Mango", slug: "mango", gender: "Men", subcategory: "Shorts", name: "Linen Shorts", price: "$49.99", tag: "New", inStock: true, category: "Mediterranean Style", description: "Lightweight linen shorts with side pockets.", sizes: ["S", "M", "L", "XL"], colors: ["Beige", "Navy", "White"] },
  { store: "Mango", slug: "mango", gender: "Men", subcategory: "Accessories", name: "Leather Belt", price: "$35.99", tag: "", inStock: true, category: "Mediterranean Style", description: "Classic leather belt with silver buckle.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Tan"] },
]

async function seed() {
  await mongoose.connect(MONGODB_URI)
  await Product.deleteMany({})
  await Product.insertMany(products)
  console.log("DONE - seeded " + products.length + " products")
  await mongoose.disconnect()
  process.exit(0)
}

seed().catch((err) => {
  console.log("ERROR: " + err.message)
  process.exit(1)
})